
"""Problem 4.ipynb
Implement the MYPY Phone Book System in Python as per Figure 3 below which allows users to add, delete, update and lookup phone numbers. The MYPY Phone Book System 
should store the individual’s Full Name and Phone Number. Your program should not allowusers to add the same number twice. On adding, deleting, updating or looking up a number, 
your program should let the user know if the operation was successful or not. On looking up a number return the full name and number of the individual; if the number is not found give 
the user the option to add the details they are looking up. The user can perform multiple actions; they can add a new entry and subsequently delete an entry without having to stop and 
start the program until they decide to quit.

Automatically generated by Colaboratory.

Original file is located at:
https://github.com/sangeeta196/Python_code_Problems"""

print("***************")
print("MYPY PHONE BOOK")
print("***************")

###Creating an empty dictionary to store "Name" and "Phone Number"###

phone_numbers={}

###Creating a user defined function with which can be called after user input###

def contact():
    global contact_choice
###contact_choice is used as a global variable###

    print('1 : Please Add New Entry')
    print('2 : Delete an Entry')
    print('3 : Update an Entry')
    print('4 : Lookup Number')
    print('5 : QUIT')

    try:
        contact_choice = int(input("Enter your number between 1 and 5: "))

### This will Deal when user enters a wrong choice###
    except ValueError:    
        print("Invalid input, Please try again!")
        contact()
 
contact()

while contact_choice !=5:

    if contact_choice==1:    ###For adding new entry###
       print("Please add name and number")
       name = input("Enter a Name: ")
       num = input("Enter the Phone Number: ")

###to ensure that the user doesnt repeat name###
       if name in phone_numbers:    
            print(name, " already exist in the phone book")
            print(phone_numbers)        
            
       elif num in phone_numbers.values():  #to ensure that the user doesnt repeat number
           print("This number already exist in the phone book")
           print(phone_numbers)  
       
       else:   ###if user enters non repeated entry then it will get updated in the dictionary###
           phone_numbers[name] = num
           print(phone_numbers)  
           
       contact() 

###To display the menu choice again to continue the process###
           
           
###To delete an entry###

    elif contact_choice==2:    
       print("So you wish to Delete an entry")
       name=input("Enter a Name to be removed: ")
       
       if name in phone_numbers:
           del phone_numbers[name]
           print(name," is successfully removed from the phone book")
           print(phone_numbers)  

     
###to print error message if entry doesn'tecist in the phone book###

       else:     
           print(name,"was not found in the phone book")
           print(phone_numbers)  
         
       contact()  

###To display the menu choice again to continue the process###

    elif contact_choice==3:    #to update entry
        print("So you wish to update a Number")
        num=input("Enter a new number to update: ")
        name=input("Enter the name for which number has to be updated: ")
        new_number={name:num}


###displaying error message if the number is repeated###
        if num in phone_numbers.values():  
            print("This number already exist in the phone book")
            print(phone_numbers)  


###to restrict updating if name doesn't exist in the phone book###
        elif name not in phone_numbers:  
            print(name, "was not found in the phone book")
            print(phone_numbers)  

###lets user to update if the number is unique and the name exist in the phone book###
        else:    
            phone_numbers.update(new_number)
            print(name, " phone number is successfully updated")
            print(phone_numbers)  
          
        contact()  
        ###To display the menu choice again to continue the process###
       
       
###to look up for a number###
    elif contact_choice==4:   
        print("You wish to look up for a Number")
        name=input("Enter the name to look up phone number: ")

###displaying phone number if the name exists in the phone book###
        if name in phone_numbers:   
            print("Phone number of ",name, " is " ,phone_numbers[name])
            print(phone_numbers)  
        
        else:   #to show error message if the name doesn't exist in phonebook
            print(name, "was not found in the phone book")
            print(phone_numbers)  
          
        contact() 
        ###To display the menu choice again to continue the process###
        
    elif contact_choice>5:
        print("Not a valid input! Please enter again")
        print("\n\n")
        contact() 
        ###To display the menu choice again to continue the process###
        
    else:
         break